# Replace the text below to customize your site
site_name: Beste
site_description: Master in Design for Emergent Futures
site_author: Beste Cebeci
copyright: Copyleft 2025 "Beste" - GNU Free Documentation License
repo_name: ""
site_url: https://beste-cebeci.github.io/mdef/  
repo_url: ""
theme:
  name: material


  features:
    -navigation.tabs
    -navigation.tabs.sticky

 
nav:
  - Home: index.md
  - About Me: about/me.md
  - MDEF:
      - LWYOI: mdef/livingwithyourownideas/index.md
      - Future Makers: mdef/futuremakers/index.md
  - Master project: project/project.md



extra_css:
  - stylesheets/extra.css

