# Replace the text below to customize your site
site_name: Beste
site_description: Master in Design for Emergent Futures
site_author: Beste Cebeci
copyright: Copyleft 2025 "Beste" - GNU Free Documentation License
repo_name: ""
site_url: https://beste-cebeci.github.io/mdef/  
repo_url: ""

nav:
  - Home: index.md
  - About Me: about/me.md
  - MDEF:
      - LWYOI: mdef/livingwithyourownideas/lwoi.md
      - Future Makers: mdef/futuremakers/fm.md
      - Unpacking: mdef/unpacking/up.md
      - Atlas of Weak Signals: mdef/atlasofweaksignals/aows.md
      - Pictorial: mdef/pictorial/pictorial.md
      - Extended Intelligences: mdef/extendedintelligences/ei.md
      - Other Species II: mdef/otherspecies2/os2.md
    



extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: black
  font:
    # See available fonts at https://fonts.google.com/
    text: Figtree
    code: Cutive Mono
  icon:
    logo: material/fish
  favicon: material/fish
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - pdf-export

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: "svg"
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css

